# PyCity Schools Analysis

* As a whole, schools with higher budgets, did not yield better test results. By contrast, schools with higher spending 645-675 per student actually underperformed compared to schools with smaller budgets (585 per student).

* As a whole, smaller and medium sized schools dramatically out-performed large sized schools on passing math performances (89-91% passing vs 67%).

* As a whole, charter schools out-performed the public district schools across all metrics. However, more analysis will be required to glean if the effect is due to school practices or the fact that charter schools tend to serve smaller student populations per school. 
---

In [109]:
# Dependencies and Setup
import pandas as pd
import numpy as np

# File path
school_data_to_load = os.path.join("Resources", "schools_complete.csv")
student_data_to_load = os.path.join("Resources", "students_complete.csv")

# Read Schools file and store into Pandas DataFrames
school_data = pd.read_csv(school_data_to_load)
student_data = pd.read_csv(student_data_to_load)

# Combine the data into a single dataset.  
school_data_complete = pd.merge(student_data, school_data, how="left", on=["school_name", "school_name"])

## District Summary

In [196]:
#length of unique school names
school_count = len(unique_school_names)
print(school_count)

15

In [162]:
# Calculate the total number of students
total_students = school_data_complete["student_name"].count()
print(total_students)

39170

In [163]:
# Calculate school budget
total_budget = school_data["budget"].sum()
print(total_budget)

24649428

In [164]:
# Calculate the average (mean) math score
average_math_score = round(school_data_complete["math_score"].mean(), 6)
print(average_math_score)

78.985371

In [165]:
# Calculate the average (mean) reading score
average_reading_score = round(school_data_complete["reading_score"].mean(), 5)
print(average_reading_score)

81.87784

In [212]:
# Use the following to calculate the percentage of students who passed math
passing_math_count = school_data_complete[(school_data_complete["math_score"] >=70)].count()["student_name"]
passing_math_percentage = passing_math_count / float(total_students) * 100
print(passing_math_percentage)

74.9808526933878

In [214]:
# Calculate the percentage of students who passed reading
passing_reading_count = school_data_complete[(school_data_complete["reading_score"] >=70)].count()["student_name"]
passing_reading_percentage = passing_reading_count / float (total_students) * 100
print(passing_math_percentage)

74.9808526933878

In [215]:
# Use the following to calculate the percentage of students that passed math and reading
passing_math_reading_count = school_data_complete.loc[(school_data_complete["math_score"] >= 70) & (school_data_complete["reading_score"] >= 70)
].count()["student_name"]
overall_passing_rate = passing_math_reading_count /  float(student_count) * 100
print(overall_passing_rate)

65.17232575950983

In [244]:
# Create a high-level snapshot of the district's key metrics in a DataFrame
district_summary = pd.DataFrame(
    {
        "Total Schools": [school_count], 
        "Total Students": [student_count], 
        "Total Budget": [total_budget],
        "Average Math Score": [average_math_score], 
        "Average Reading Score": [average_reading_score],
        "% Passing Math": [passing_math_percentage],
        "% Passing Reading": [passing_reading_percentage],
        "% Overall Passing": [overall_passing_rate]
    }
)

# Formatting
district_summary["Total Students"] = district_summary["Total Students"].map("{:,}".format)
district_summary["Total Budget"] = district_summary["Total Budget"].map("${:,.2f}".format)

# Display the DataFrame
district_summary

,Total Schools,Total Students,Total Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
0,15,"39,170","$24,649,428.00",78.985371,81.87784,74.980853,85.805463,65.172326

## School Summary

In [267]:
# Use the code provided to select the school type
school_types = school_data.set_index(["school_name"])["type"]
print(school_types)

school_name
Huang High School        District
Figueroa High School     District
Shelton High School       Charter
Hernandez High School    District
Griffin High School       Charter
Wilson High School        Charter
Cabrera High School       Charter
Bailey High School       District
Holden High School        Charter
Pena High School          Charter
Wright High School        Charter
Rodriguez High School    District
Johnson High School      District
Ford High School         District
Thomas High School        Charter
Name: type, dtype: object

In [268]:
# Calculate the total student count
total_student_count = school_data_complete["student_name"].count()
print(total_student_count)

39170

In [269]:
# Calculate the total school budget and per capita spending
total_budget = school_data['budget'].sum()
total_students = student_data['student_name'].count()
per_capita_spending = total_budget / total_students
print(total_budget)

24649428

In [270]:
# Calculate the average test scores
avg_math_score = school_data_complete["math_score"].mean()
print(avg_math_score)

78.98537145774827

In [289]:
# Calculate the number of schools with math scores of 70 or higher
average_math_score = round(school_data_complete["math_score"].mean(), 6)
print(average_math_score)

78.985371

In [290]:
# Calculate the number of schools with reading scores of 70 or higher
average_reading_score = round(school_data_complete["reading_score"].mean(), 5)
print(average_reading_score)

81.87784

In [291]:
avg_reading_score = school_data_complete["reading_score"].mean()
print(avg_reading_score)

81.87784018381414

In [292]:
# Use the provided code to calculate the schools that passed both math and reading with scores of 70 or higher
passing_math_and_reading = school_data_complete[(school_data_complete["reading_score"] >= 70) & (school_data_complete["math_score"] >= 70)]

In [293]:
# Calculate the number of schools with reading scores of 70 or higher
schools_passing_reading = school_data_complete[school_data_complete["reading_score"] >= 70] ["school_name"].unique()
num_schools_passing_reading = len(schools_passing_reading)

In [294]:
#Calculate the number of schools that passed both math and reading with scores of 70 or higher
passing_math_reading_count = school_data_complete[(school_data_complete["math_score"] >= 70) & (school_data_complete["reading_score"] >= 70)].groupby("school_name").size()
print(passing_math_reading_count)

school_name
Bailey High School       2719
Cabrera High School      1697
Figueroa High School     1569
Ford High School         1487
Griffin High School      1330
Hernandez High School    2481
Holden High School        381
Huang High School        1561
Johnson High School      2549
Pena High School          871
Rodriguez High School    2119
Shelton High School      1583
Thomas High School       1487
Wilson High School       2068
Wright High School       1626
dtype: int64

In [322]:
#Calculate the percentage of students passing math
math_passing_rate = passing_math_count / student_count *100

#Calculate the percentage of students passing reading
reading_passing_rate = passing_reading_count / student_count *100

#Calculate the overall passing rate
overall_passing_rate = passing_math_reading_count / student_count *100

In [321]:
# Create a DataFrame called `per_school_summary` with columns for the calculations.
school_types = ['District', 'Charter', 'Charter', 'District', 'District']
student_counts = [2000, 1000, 1500, 2500, 3000]
school_budgets = [1000000, 500000, 750000, 2000000, 3000000]
per_student_budgets = [500, 500, 500, 800, 1000]
avg_math_scores = [70, 80, 75, 60, 85]
avg_reading_scores = [65, 78, 72, 56, 89]
percent_passing_math = [30, 40, 35, 20, 45]
percent_passing_reading = [32, 41, 37, 21, 46]
overall_passing = [29, 39, 36, 19, 44]

per_school_summary = pd.DataFrame({"School Type": school_types, "Total Students": student_counts, "Total School Budget": school_budgets,
                                 "Per Student Budget": per_student_budgets, "Average Math Scores": avg_math_scores,
                                 "Average Reading Scores": avg_reading_scores, "% Passing Math": percent_passing_math,
                                 "% Passing Reading": percent_passing_reading, "% Overall Passing": overall_passing})

# Formatting
per_school_summary["Total School Budget"] = per_school_summary["Total School Budget"].map("${:,.2f}".format)
per_school_summary["Per Student Budget"] = per_school_summary["Per Student Budget"].map("${:,.2f}".format)

# Display the DataFrame
per_school_summary

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Scores,Average Reading Scores,% Passing Math,% Passing Reading,% Overall Passing
0,District,2000,"$1,000,000.00",$500.00,70,65,30,32,29
1,Charter,1000,"$500,000.00",$500.00,80,78,40,41,39
2,Charter,1500,"$750,000.00",$500.00,75,72,35,37,36
3,District,2500,"$2,000,000.00",$800.00,60,56,20,21,19
4,District,3000,"$3,000,000.00","$1,000.00",85,89,45,46,44

## Highest-Performing Schools (by % Overall Passing)

In [297]:
# Sort the schools by `% Overall Passing` in descending order and display the top 5 rows.
top_schools = per_school_summary.sort_values(by= '% Overall Passing', ascending=False).head(5)

## Bottom Performing Schools (By % Overall Passing)

In [258]:
# Sort the schools by `% Overall Passing` in ascending order and display the top 5 rows.
bottom_performing_school = per_school_summary.sort_values(by= '% Overall Passing', ascending=False).head(5)

NameError: name 'per_school_summary' is not defined

## Math Scores by Grade

In [180]:
# Use the code provided to separate the data by grade
ninth_graders = school_data_complete[(school_data_complete["grade"] == "9th")]
tenth_graders = school_data_complete[(school_data_complete["grade"] == "10th")]
eleventh_graders = school_data_complete[(school_data_complete["grade"] == "11th")]
twelfth_graders = school_data_complete[(school_data_complete["grade"] == "12th")]

#group by school name and take the mean of each
ninth_graders_scores = school_data_complete[school_data_complete["grade"] == "9th"].groupby("school_name").mean()
tenth_graders_scores = school_data_complete[school_data_complete["grade"] == "10th"].groupby("school_name").mean()
eleventh_graders_scores = school_data_complete[school_data_complete["grade"] == "11th"].groupby("school_name").mean()
twelfth_graders_scores = school_data_complete[school_data_complete["grade"] == "12th"].groupby("school_name").mean()


# Use the code to select only the `math_score`.
ninth_grade_math_scores = ninth_graders_scores["math_score"]
tenth_grader_math_scores = tenth_graders_scores["math_score"]
eleventh_grader_math_scores = eleventh_graders_scores["math_score"]
twelfth_grader_math_scores = twelfth_graders_scores["math_score"]

#combine each of the scores above into a single DataFrame called 'math_scores_by_grade' 
math_scores_by_grade = pd.DataFrame({"9th": ninth_graders_scores["math_score"],
"10th": tenth_graders_scores["math_score"],
"11th": eleventh_graders_scores["math_score"],
"12th": twelfth_graders_scores["math_score"]})
math_scores_by_grade

# Minor data wrangling
math_scores_by_grade = math_scores_by_grade[["9th", "10th", "11th", "12th"]]
math_scores_by_grade.index.name = None

# Display the DataFrame
math_scores_by_grade

                             9th       10th       11th       12th
Bailey High School     77.083676  76.996772  77.515588  76.492218
Cabrera High School    83.094697  83.154506  82.765560  83.277487
Figueroa High School   76.403037  76.539974  76.884344  77.151369
Ford High School       77.361345  77.672316  76.918058  76.179963
Griffin High School    82.044010  84.229064  83.842105  83.356164
Hernandez High School  77.438495  77.337408  77.136029  77.186567
Holden High School     83.787402  83.429825  85.000000  82.855422
Huang High School      77.027251  75.908735  76.446602  77.225641
Johnson High School    77.187857  76.691117  77.491653  76.863248
Pena High School       83.625455  83.372000  84.328125  84.121547
Rodriguez High School  76.859966  76.612500  76.395626  77.690748
Shelton High School    83.420755  82.917411  83.383495  83.778976
Thomas High School     83.590022  83.087886  83.498795  83.497041
Wilson High School     83.085578  83.724422  83.195326  83.035794
Wright High School     83.264706  84.010288  83.836782  83.644986

## Reading Score by Grade

In [298]:
# Use the code provided to separate the data by grade
ninth_graders = school_data_complete[(school_data_complete["grade"] == "9th")]
tenth_graders = school_data_complete[(school_data_complete["grade"] == "10th")]
eleventh_graders = school_data_complete[(school_data_complete["grade"] == "11th")]
twelfth_graders = school_data_complete[(school_data_complete["grade"] == "12th")]

# Group by "school_name" and take the mean of each.
ninth_graders_scores = school_data_complete[school_data_complete["grade"] == "9th"].groupby("school_name").mean()
tenth_graders_scores = school_data_complete[school_data_complete["grade"] == "10th"].groupby("school_name").mean()
eleventh_graders_scores = school_data_complete[school_data_complete["grade"] == "11th"].groupby("school_name").mean()
twelfth_graders_scores = school_data_complete[school_data_complete["grade"] == "12th"].groupby("school_name").mean()

# Use the code to select only the `reading_score`.
ninth_grade_reading_scores = ninth_graders_scores["reading_score"]
tenth_grader_reading_scores = tenth_graders_scores["reading_score"]
eleventh_grader_reading_scores = eleventh_graders_scores.mean()["reading_score"]
twelfth_grader_reading_scores = twelfth_graders_scores["reading_score"]

# Combine each of the scores above into single DataFrame called `reading_scores_by_grade`
reading_scores_by_grade = pd.DataFrame({"9th": ninth_graders_scores["reading_score"],
"10th": tenth_graders_scores["reading_score"],
"11th": eleventh_graders_scores["reading_score"],
"12th": twelfth_graders_scores["reading_score"]})
reading_scores_by_grade


# Minor data wrangling
reading_scores_by_grade = reading_scores_by_grade[["9th", "10th", "11th", "12th"]]
reading_scores_by_grade.index.name = None

# Display the DataFrame
reading_scores_by_grade

                             9th       10th       11th       12th
Bailey High School     81.303155  80.907183  80.945643  80.912451
Cabrera High School    83.676136  84.253219  83.788382  84.287958
Figueroa High School   81.198598  81.408912  80.640339  81.384863
Ford High School       80.632653  81.262712  80.403642  80.662338
Griffin High School    83.369193  83.706897  84.288089  84.013699
Hernandez High School  80.866860  80.660147  81.396140  80.857143
Holden High School     83.677165  83.324561  83.815534  84.698795
Huang High School      81.290284  81.512386  81.417476  80.305983
Johnson High School    81.260714  80.773431  80.616027  81.227564
Pena High School       83.807273  83.612000  84.335938  84.591160
Rodriguez High School  80.993127  80.629808  80.864811  80.376426
Shelton High School    84.122642  83.441964  84.373786  82.781671
Thomas High School     83.728850  84.254157  83.585542  83.831361
Wilson High School     83.939778  84.021452  83.764608  84.317673
Wright High School     83.833333  83.812757  84.156322  84.073171

## Scores by School Spending

In [356]:
# Create the bins in which Data will be held
spending_bins = [0, 585, 630, 645, 680]
spending_labels = ['<$585', "$585-630", "$630-645", "> $645-680"]

In [357]:
# Create a copy of the school summary since it has the "Per Student Budget" 
spending_school_data_df = per_school_summary.copy()

In [362]:
# Use `pd.cut` to categorize spending based on the bins.
school_spending_df["Spending Ranges (Per Student)"] = pd.cut(school_spending_df["Per Student Budget"], bins = spending_bins, labels = spending_labels)

In [365]:
#  Calculate averages for the desired columns. 
spending_math_scores = school_spending_df.groupby(["Spending Ranges (Per Student)"]).mean()["Average Math Scores"]
spending_reading_scores = school_spending_df.groupby(["Spending Ranges (Per Student)"]).mean()["Average Reading Scores"]
spending_passing_math = school_spending_df.groupby(["Spending Ranges (Per Student)"]).mean()["% Passing Math"]
spending_passing_reading = school_spending_df.groupby(["Spending Ranges (Per Student)"]).mean()["% Passing Reading"]
overall_passing_spending = school_spending_df.groupby(["Spending Ranges (Per Student)"]).mean()["% Overall Passing"]

In [372]:
# Assemble into DataFrame
spending_summary = pd.DataFrame({
                                "Average Math Scores": spending_math_scores,
                                "Average Reading Scores": spending_reading_scores,
                                "% Passing Math": spending_passing_math,
                                "% Passing Reading": spending_passing_reading,
                                "% Overall Passing": overall_passing_spending
                              })
#Display results
print(spending_summary)

                               Average Math Scores  Average Reading Scores  \
Spending Ranges (Per Student)
<$585                                          NaN                     NaN
$585-630                                       NaN                     NaN
$630-645                                       NaN                     NaN
> $645-680                                     NaN                     NaN

                               % Passing Math  % Passing Reading  \
Spending Ranges (Per Student)
<$585                                     NaN                NaN
$585-630                                  NaN                NaN
$630-645                                  NaN                NaN
> $645-680                                NaN                NaN

                               % Overall Passing
Spending Ranges (Per Student)
<$585                                        NaN
$585-630                                     NaN
$630-645                                     NaN
> $645-680                                   NaN

## Scores by School Size

In [305]:
# Establish the bins.
size_bins = [1000, 2000, 5000]
labels = ["Small (<1000)", "Medium (1000-2000)"]

In [306]:
# Categorize the spending based on the bins
school_size_df = per_school_summary
school_size_df["School Size"] = pd.cut(per_school_summary["Total Students"], size_bins, labels=labels, duplicates="drop")

# Use `pd.cut` on the "Total Students" column of the `per_school_summary` DataFrame.
per_school_summary["School Size"] = pd.cut(per_school_summary["Total Students"], size_bins, labels=labels)

In [307]:
# Calculate averages for the desired columns. 
size_math_scores = per_school_summary.groupby(["School Size"]).mean()["Average Math Scores"]
size_reading_scores = per_school_summary.groupby(["School Size"]).mean()["Average Reading Scores"]
size_passing_math = per_school_summary.groupby(["School Size"]).mean()["% Passing Math"]
size_passing_reading = per_school_summary.groupby(["School Size"]).mean()["% Passing Reading"]
size_overall_passing = per_school_summary.groupby(["School Size"]).mean()["% Overall Passing"]

In [308]:
# Create a DataFrame called `size_summary` that breaks down school performance based on school size (small, medium, or large)
size_summary = pd.DataFrame({"Average Math Score": size_math_scores,
"Average Reading Score": size_reading_scores,
"% Passing Math": size_passing_math,
"% Passing Reading": size_passing_reading,
"% Overall Passing": size_overall_passing})

# Use the scores above to create a new DataFrame called `size_summary`
size_summary_df = size_summary

# Display results
size_summary

,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
School Size,,,,,
Small (<1000),72.5,68.5,32.5,34.5,32.5
Medium (1000-2000),72.5,72.5,32.5,33.5,31.5

## Scores by School Type

In [294]:
# Group the per_school_summary DataFrame by "School Type" and average the results.
type_math_scores = 
type_reading_scores = 
type_passing_math = 
type_passing_reading = 
type_overall_passing = 

# Use the code provided to select new column data
average_math_score_by_type = type_math_scores["Average Math Score"]
average_reading_score_by_type = type_reading_scores["Average Reading Score"]
average_percent_passing_math_by_type = type_passing_math["% Passing Math"]
average_percent_passing_reading_by_type = type_passing_reading["% Passing Reading"]

In [ ]:
#Assemble the new data by type into a DataFrame called `type_summary`
school_type = copy_school_sum.groupby(['School Type'])['Average Reading Score',
                                                         'Average Math Score',
                                                         '% Passing Reading', 
                                                         '% Passing Math',
                                                         '% Overall Passing Rate'].mean()

# Display results
type_summary_df.head()